---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:  # Use [] if empty
  - 'App Store'
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - TV

dockitems_persist:
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
#  pos: 3,
- name: "Slack"
  path: "/Applications/Slack.app/"
- name: "iTerm"
  path: "/Applications/iTerm.app/"
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
- name: "Spotify"
  path: "/Applications/Spotify.app/"
- name: "Notion"
  path: "/Applications/Notion.app/"

# Not using
configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/rwegener2/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/repos/GitHub/dotfiles
dotfiles_files:
  - .gitconfig
  - .zshrc
  - .osx
  - .condarc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # Python build dependencies
  # see https://github.com/pyenv/pyenv/wiki#suggested-build-environment
  - openssl
  - readline
  - sqlite3
  - xz
  - zlib
  - tcl-tk
  # Everything else
  - awscli
  - git
  - node
  - netcdf
  - pyenv
  - watch
  - wget

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-acrobat-reader
  - docker
  - iterm2
  - google-chrome
  - mactex
  - notion
  - qgis
  - slack
  - spotify
  - texstudio
  - visual-studio-code
  - zoom
  - zotero

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/repos/GitHub/dotfiles/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
# pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Original repo from @geerlingguy had example of configuring Sublime. 
# Refer to that if configuring vscode is ever desired.

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
