---
####
# Installing python - pyenv
####
- name: Install Python 12 with pyenv
  command: pyenv install 3.12.1
  args:
    creates: /Users/rwegener/.pyenv/versions/3.12.1

- name: Set Python 12 as the global default
  command: pyenv global 3.12.1

####
# Installing python - miniconda
####
- name: Check if Miniconda is installed
  stat: # check if $HOME/miniconda3/LICENSE.txt exists
    path: $HOME/miniconda3/LICENSE.txt
  register: installed

- block:
    - name: "end play if nothing to upgrade"
      debug:
        msg: "nothing to upgrade, ending play"

    - meta: end_play
  when: installed.stat.exists

- name: Download latest version of Miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    dest: /tmp/install-miniconda.sh
    # checksum: md5:7406579393427eaf9bc0e094dcd3c66d1e1b93ee9db4e7686d0a72ea5d7c0ce5
    mode: 0550
- name: Create conda folder
  become: True
  file:
    path: $HOME/miniconda3
    state: directory
    # owner: ubuntu
    mode: 755
    recurse: yes
- name: Run the installer
  shell: /tmp/install-miniconda.sh -b -u -p $HOME/miniconda3
- name: Remove the installer
  file:
    state: absent
    path: /tmp/install-miniconda.sh

- name: Initalize miniconda in zsh
  command: $HOME/miniconda3/bin/conda init zsh

####
# Configuring miniconda
####
# Future improvement -- figure out how to check if this has already
# happened so they don't have to get reinstalled every time.
- name: Install global package from default channel - nb_conda_kernels
  command: $HOME/miniconda3/condabin/conda install -n base nb_conda_kernels jupyterlab

- name: Install global package from conda-forge - JupyterLab
  command: $HOME/miniconda3/condabin/conda install -n base -c conda-forge jupyterlab

# Alternate route: could include a .config file for conda the dotfiles
# - name: Set the default conda channel as conda-forge
#   command: $HOME/miniconda3/condabin/conda config --add channels conda-forge

# - name: Set the strict channel priority
#   command: $HOME/miniconda3/condabin/conda config --set channel_priority strict
