---
# Install ohmyzsh and plugins
- name: Install ohmyzsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -
  args:
    creates: $HOME/.oh-my-zsh

- name: ohmyzsh plugin zsh-syntax-highlighting 
  command: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  args:
    creates: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: ohmyzsh plugin zsh-autosuggestions 
  command: git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  args:
    creates: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
